import {
  enquiry,
  eventPackage,
  galleryCategory,
  galleryItem,
  navigation,
  page,
  partner,
  siteSettings,
  testimonial,
} from "./documents";
import { ctaButton, navItem, portableBody, seo, socialLink } from "./objects";
import {
  contactBlock,
  cta,
  faq,
  featureGrid,
  gallery,
  hero,
  imageBlock,
  packageGrid,
  partnerGrid,
  richText,
  statistics,
  testimonials,
  textAndImage,
} from "./sections";

export const schemaTypes = [
  page,
  eventPackage,
  galleryCategory,
  galleryItem,
  partner,
  testimonial,
  navigation,
  siteSettings,
  enquiry,
  seo,
  ctaButton,
  portableBody,
  navItem,
  socialLink,
  hero,
  richText,
  textAndImage,
  imageBlock,
  gallery,
  partnerGrid,
  packageGrid,
  featureGrid,
  testimonials,
  statistics,
  faq,
  cta,
  contactBlock,
];
